name: Build and push docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-back-end:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        working-directory: .
        run: docker build -t ghcr.io/${{ github.actor }}/creative-nest .
      - name: Docker login
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: docker push ghcr.io/${{ github.actor }}/creative-nest